name: Check GET request

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check_request:
    runs-on: ubuntu-latest

    steps:
    - name: Check GET request
      id: check
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
      run: |
        npm install puppeteer
        node -e "
        const puppeteer = require('puppeteer');
        (async () => {
          const browser = await puppeteer.launch();
          const page = await browser.newPage();
          let success = false;
          for (let i = 1; i <= 100; i++) {
            try {
              await page.goto('https://appulate.com/build/scripts/pages/insured/insured-grid/index.entry.js?v=5PMfDUNkrQI9hycn6IpwrJmrsd1iIMG29vYtjZwVEeY', {waitUntil: 'networkidle2'});
              console.log('Request succeeded on attempt ' + i);
              success = true;
              break;
            } catch (err) {
              console.log('Request failed on attempt ' + i);
            }
          }
          await browser.close();
          if (!success) {
            process.exit(1);
          }
        })();
        "

    - name: Check status
      run: |
        if [[ "${{ steps.check.exitcode }}" -ne 0 ]]; then
          echo "Request failed"
          exit 1
        else
          echo "Request succeeded"
        fi
