name: Check GET request

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check_request:
    runs-on: ubuntu-latest

    steps:
      - name: Check GET request
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Make request
        uses: wow-actions/puppeteer@v1.2
        with:
          headless: true
          puppeteer-version: '10.x'
          args: |
            for (let i = 1; i <= 100; i++) {
              const page = await browser.newPage();
              try {
                await page.goto('https://appulate.com/build/scripts/pages/insured/insured-grid/index.entry.js?v=5PMfDUNkrQI9hycn6IpwrJmrsd1iIMG29vYtjZwVEeY', {waitUntil: 'networkidle2'});
                console.log('Request succeeded on attempt ' + i);
              } catch (err) {
                console.log('Request failed on attempt ' + i);
                await browser.close();
                process.exit(1);
              }
              await page.close();
            }
          waitUntil: networkidle2
      - name: Check status
        run: |
          if [[ "${{ job.status }}" == "failure" ]]; then
            echo "Request failed"
            exit 1
          else
            echo "Request succeeded"
