name: Domain Expiration Checker

on:
  schedule:
    - cron: '0 0 * * *'  # Runs the action every day at midnight UTC
  workflow_dispatch:  # Allows the workflow to be manually triggered

jobs:
  check_expiration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install whois

    - name: Check domain expiration
      run: |
        for domain in $(cat domains.json | jq -r '.domains[]'); do
          expiration_date=$(whois $domain | grep 'Registry Expiry Date:' | awk '{print $4}')
          today_date=$(date '+%Y-%m-%d')
          days_left=$(( ($(date -d $expiration_date +%s) - $(date -d $today_date +%s)) / (60*60*24) ))
          echo "Domain: $domain. Expiration date: $expiration_date. Days left: $days_left"
          if [[ $days_left -lt 14 ]]; then
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Domain *'"$domain"'* is expiring in *'"$days_left"'* days."}' $SLACK_WEBHOOK_URL
          fi
        done
